### ISSUE TITLE
The right way to deploy ros on nginx with SSL

### ISSUE THREAD

**Issue by jaisontj** [realm/realm-object-server#310]
## Goals

Hi, I seem to be having the same issue as [this](https://github.com/realm/realm-object-server/issues/294) one. 

Here is what I have done,
I have dockerized ros and am trying to deploy it on nginx with SSL enabled. Since the requests to ros are behind a gateway I have not enabled https on the ros. The server is currently running at https://ros.critique72.hasura-app.io/. I tried connecting to this via Realm studio with

url -> https://ros.dishonestly26.hasura-app.io/
default username and password

While the login succeeds, I am not able to view the Realms/Users and Logs are empty.

## Expected Results

Realm Studio should display Realms and User information

## Actual Results

Login succeeds but no data is shown, just a loading indicator for each tab.

## Steps to Reproduce

Try connecting to the following using realm studio

url -> https://ros.dishonestly26.hasura-app.io/
default username and password

## Version of Realm and Tooling

- Realm Object Server Version: 2.0.22
- Flavor: Developer

**Comment by morten-krogh** [comment]
Hi @jaisontj 
Sorry for the late reply.
I tried connecting to your server, but it seems like you have taken it offline.
Do you still have this problem?

**Comment by guatedude2** [comment]
I'm having a similar issue. Here's how I reproduced it locally with a self-signed cert

used docker compose for this example:

```
version: '3'
services:
  web:
    image: nginx
    depends_on:
      - realm_db
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web/ssl:/var/opt/ssl:ro
    ports:
      - 9080:9080
      - 9443:9443
  realm_db:
    image: realm/realm-object-server:latest
    environment:
      - ROS_TOS_EMAIL_ADDRESS=admin@local.com
```

nginx.conf file

```
upstream db {
    server realm_db:9080;
}
server {
    listen 9080;
    listen 9443 ssl;
    ssl_certificate /var/opt/ssl/server.crt;
    ssl_certificate_key /var/opt/ssl/server.key;
    location / {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://db;
    }
}
```

Here are the [Heruku instructions](https://devcenter.heroku.com/articles/ssl-certificate-self) to generate a self signed cert if you need one.

After that I try to connect via Real Studio like so:

<img width="756" alt="screen shot 2018-05-05 at 12 43 38 pm" src="https://user-images.githubusercontent.com/918429/39665424-06408858-5062-11e8-8cc8-fc33aedf67df.png">

And get a blank screen like this one:

<img width="1136" alt="screen shot 2018-05-05 at 12 43 58 pm" src="https://user-images.githubusercontent.com/918429/39665425-064b5a94-5062-11e8-84df-269b2a2764c5.png">
